# Amount of money to invest
cache: 10000

# List of stocks to invest in
stocks:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - TSLA

alpaca:
  api-key: "your-alpaca-api-key"

telegram:
  bot-token: "your-telegram-bot-token"
