// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kasaderos/camel/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

type AnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalyticsService) EXPECT() *AnalyticsService_Expecter {
	return &AnalyticsService_Expecter{mock: &_m.Mock}
}

// FetchStockScores provides a mock function with given fields: ctx, stockIDs
func (_m *AnalyticsService) FetchStockScores(ctx context.Context, stockIDs []model.StockID) (map[model.StockID]float64, error) {
	ret := _m.Called(ctx, stockIDs)

	if len(ret) == 0 {
		panic("no return value specified for FetchStockScores")
	}

	var r0 map[model.StockID]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.StockID) (map[model.StockID]float64, error)); ok {
		return rf(ctx, stockIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.StockID) map[model.StockID]float64); ok {
		r0 = rf(ctx, stockIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.StockID]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.StockID) error); ok {
		r1 = rf(ctx, stockIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsService_FetchStockScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchStockScores'
type AnalyticsService_FetchStockScores_Call struct {
	*mock.Call
}

// FetchStockScores is a helper method to define mock.On call
//   - ctx context.Context
//   - stockIDs []model.StockID
func (_e *AnalyticsService_Expecter) FetchStockScores(ctx interface{}, stockIDs interface{}) *AnalyticsService_FetchStockScores_Call {
	return &AnalyticsService_FetchStockScores_Call{Call: _e.mock.On("FetchStockScores", ctx, stockIDs)}
}

func (_c *AnalyticsService_FetchStockScores_Call) Run(run func(ctx context.Context, stockIDs []model.StockID)) *AnalyticsService_FetchStockScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.StockID))
	})
	return _c
}

func (_c *AnalyticsService_FetchStockScores_Call) Return(_a0 map[model.StockID]float64, _a1 error) *AnalyticsService_FetchStockScores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsService_FetchStockScores_Call) RunAndReturn(run func(context.Context, []model.StockID) (map[model.StockID]float64, error)) *AnalyticsService_FetchStockScores_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
