// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kasaderos/camel/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Exchanger is an autogenerated mock type for the Exchanger type
type Exchanger struct {
	mock.Mock
}

type Exchanger_Expecter struct {
	mock *mock.Mock
}

func (_m *Exchanger) EXPECT() *Exchanger_Expecter {
	return &Exchanger_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, orderID
func (_m *Exchanger) CancelOrder(ctx context.Context, orderID string) error {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exchanger_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type Exchanger_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *Exchanger_Expecter) CancelOrder(ctx interface{}, orderID interface{}) *Exchanger_CancelOrder_Call {
	return &Exchanger_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderID)}
}

func (_c *Exchanger_CancelOrder_Call) Run(run func(ctx context.Context, orderID string)) *Exchanger_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Exchanger_CancelOrder_Call) Return(_a0 error) *Exchanger_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Exchanger_CancelOrder_Call) RunAndReturn(run func(context.Context, string) error) *Exchanger_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMarketOrder provides a mock function with given fields: ctx, symbol, qty, side
func (_m *Exchanger) CreateMarketOrder(ctx context.Context, symbol string, qty float64, side model.OrderSide) (*model.Order, error) {
	ret := _m.Called(ctx, symbol, qty, side)

	if len(ret) == 0 {
		panic("no return value specified for CreateMarketOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, model.OrderSide) (*model.Order, error)); ok {
		return rf(ctx, symbol, qty, side)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, model.OrderSide) *model.Order); ok {
		r0 = rf(ctx, symbol, qty, side)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, model.OrderSide) error); ok {
		r1 = rf(ctx, symbol, qty, side)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exchanger_CreateMarketOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMarketOrder'
type Exchanger_CreateMarketOrder_Call struct {
	*mock.Call
}

// CreateMarketOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - qty float64
//   - side model.OrderSide
func (_e *Exchanger_Expecter) CreateMarketOrder(ctx interface{}, symbol interface{}, qty interface{}, side interface{}) *Exchanger_CreateMarketOrder_Call {
	return &Exchanger_CreateMarketOrder_Call{Call: _e.mock.On("CreateMarketOrder", ctx, symbol, qty, side)}
}

func (_c *Exchanger_CreateMarketOrder_Call) Run(run func(ctx context.Context, symbol string, qty float64, side model.OrderSide)) *Exchanger_CreateMarketOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(model.OrderSide))
	})
	return _c
}

func (_c *Exchanger_CreateMarketOrder_Call) Return(_a0 *model.Order, _a1 error) *Exchanger_CreateMarketOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Exchanger_CreateMarketOrder_Call) RunAndReturn(run func(context.Context, string, float64, model.OrderSide) (*model.Order, error)) *Exchanger_CreateMarketOrder_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOrder provides a mock function with given fields: ctx, orderID
func (_m *Exchanger) FetchOrder(ctx context.Context, orderID string) (*model.Order, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FetchOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exchanger_FetchOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOrder'
type Exchanger_FetchOrder_Call struct {
	*mock.Call
}

// FetchOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *Exchanger_Expecter) FetchOrder(ctx interface{}, orderID interface{}) *Exchanger_FetchOrder_Call {
	return &Exchanger_FetchOrder_Call{Call: _e.mock.On("FetchOrder", ctx, orderID)}
}

func (_c *Exchanger_FetchOrder_Call) Run(run func(ctx context.Context, orderID string)) *Exchanger_FetchOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Exchanger_FetchOrder_Call) Return(_a0 *model.Order, _a1 error) *Exchanger_FetchOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Exchanger_FetchOrder_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *Exchanger_FetchOrder_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPrice provides a mock function with given fields: ctx, assetID
func (_m *Exchanger) FetchPrice(ctx context.Context, assetID string) (float64, time.Time, error) {
	ret := _m.Called(ctx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for FetchPrice")
	}

	var r0 float64
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, time.Time, error)); ok {
		return rf(ctx, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, assetID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) time.Time); ok {
		r1 = rf(ctx, assetID)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, assetID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Exchanger_FetchPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPrice'
type Exchanger_FetchPrice_Call struct {
	*mock.Call
}

// FetchPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
func (_e *Exchanger_Expecter) FetchPrice(ctx interface{}, assetID interface{}) *Exchanger_FetchPrice_Call {
	return &Exchanger_FetchPrice_Call{Call: _e.mock.On("FetchPrice", ctx, assetID)}
}

func (_c *Exchanger_FetchPrice_Call) Run(run func(ctx context.Context, assetID string)) *Exchanger_FetchPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Exchanger_FetchPrice_Call) Return(_a0 float64, _a1 time.Time, _a2 error) *Exchanger_FetchPrice_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Exchanger_FetchPrice_Call) RunAndReturn(run func(context.Context, string) (float64, time.Time, error)) *Exchanger_FetchPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewExchanger creates a new instance of Exchanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Exchanger {
	mock := &Exchanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
