// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kasaderos/camel/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PortfolioRepository is an autogenerated mock type for the PortfolioRepository type
type PortfolioRepository struct {
	mock.Mock
}

type PortfolioRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PortfolioRepository) EXPECT() *PortfolioRepository_Expecter {
	return &PortfolioRepository_Expecter{mock: &_m.Mock}
}

// CreatePortfolio provides a mock function with given fields: ctx, p
func (_m *PortfolioRepository) CreatePortfolio(ctx context.Context, p model.Portfolio) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePortfolio")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Portfolio) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioRepository_CreatePortfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePortfolio'
type PortfolioRepository_CreatePortfolio_Call struct {
	*mock.Call
}

// CreatePortfolio is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.Portfolio
func (_e *PortfolioRepository_Expecter) CreatePortfolio(ctx interface{}, p interface{}) *PortfolioRepository_CreatePortfolio_Call {
	return &PortfolioRepository_CreatePortfolio_Call{Call: _e.mock.On("CreatePortfolio", ctx, p)}
}

func (_c *PortfolioRepository_CreatePortfolio_Call) Run(run func(ctx context.Context, p model.Portfolio)) *PortfolioRepository_CreatePortfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Portfolio))
	})
	return _c
}

func (_c *PortfolioRepository_CreatePortfolio_Call) Return(_a0 error) *PortfolioRepository_CreatePortfolio_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioRepository_CreatePortfolio_Call) RunAndReturn(run func(context.Context, model.Portfolio) error) *PortfolioRepository_CreatePortfolio_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPortfolio provides a mock function with given fields: ctx, id
func (_m *PortfolioRepository) FetchPortfolio(ctx context.Context, id string) (model.Portfolio, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchPortfolio")
	}

	var r0 model.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Portfolio, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Portfolio); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Portfolio)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioRepository_FetchPortfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPortfolio'
type PortfolioRepository_FetchPortfolio_Call struct {
	*mock.Call
}

// FetchPortfolio is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PortfolioRepository_Expecter) FetchPortfolio(ctx interface{}, id interface{}) *PortfolioRepository_FetchPortfolio_Call {
	return &PortfolioRepository_FetchPortfolio_Call{Call: _e.mock.On("FetchPortfolio", ctx, id)}
}

func (_c *PortfolioRepository_FetchPortfolio_Call) Run(run func(ctx context.Context, id string)) *PortfolioRepository_FetchPortfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PortfolioRepository_FetchPortfolio_Call) Return(_a0 model.Portfolio, _a1 error) *PortfolioRepository_FetchPortfolio_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioRepository_FetchPortfolio_Call) RunAndReturn(run func(context.Context, string) (model.Portfolio, error)) *PortfolioRepository_FetchPortfolio_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePortfolio provides a mock function with given fields: ctx, p
func (_m *PortfolioRepository) UpdatePortfolio(ctx context.Context, p model.Portfolio) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePortfolio")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Portfolio) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioRepository_UpdatePortfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePortfolio'
type PortfolioRepository_UpdatePortfolio_Call struct {
	*mock.Call
}

// UpdatePortfolio is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.Portfolio
func (_e *PortfolioRepository_Expecter) UpdatePortfolio(ctx interface{}, p interface{}) *PortfolioRepository_UpdatePortfolio_Call {
	return &PortfolioRepository_UpdatePortfolio_Call{Call: _e.mock.On("UpdatePortfolio", ctx, p)}
}

func (_c *PortfolioRepository_UpdatePortfolio_Call) Run(run func(ctx context.Context, p model.Portfolio)) *PortfolioRepository_UpdatePortfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Portfolio))
	})
	return _c
}

func (_c *PortfolioRepository_UpdatePortfolio_Call) Return(_a0 error) *PortfolioRepository_UpdatePortfolio_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioRepository_UpdatePortfolio_Call) RunAndReturn(run func(context.Context, model.Portfolio) error) *PortfolioRepository_UpdatePortfolio_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePortfolioStock provides a mock function with given fields: ctx, stock
func (_m *PortfolioRepository) UpdatePortfolioStock(ctx context.Context, stock model.PortfolioStock) error {
	ret := _m.Called(ctx, stock)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePortfolioStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PortfolioStock) error); ok {
		r0 = rf(ctx, stock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioRepository_UpdatePortfolioStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePortfolioStock'
type PortfolioRepository_UpdatePortfolioStock_Call struct {
	*mock.Call
}

// UpdatePortfolioStock is a helper method to define mock.On call
//   - ctx context.Context
//   - stock model.PortfolioStock
func (_e *PortfolioRepository_Expecter) UpdatePortfolioStock(ctx interface{}, stock interface{}) *PortfolioRepository_UpdatePortfolioStock_Call {
	return &PortfolioRepository_UpdatePortfolioStock_Call{Call: _e.mock.On("UpdatePortfolioStock", ctx, stock)}
}

func (_c *PortfolioRepository_UpdatePortfolioStock_Call) Run(run func(ctx context.Context, stock model.PortfolioStock)) *PortfolioRepository_UpdatePortfolioStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PortfolioStock))
	})
	return _c
}

func (_c *PortfolioRepository_UpdatePortfolioStock_Call) Return(_a0 error) *PortfolioRepository_UpdatePortfolioStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioRepository_UpdatePortfolioStock_Call) RunAndReturn(run func(context.Context, model.PortfolioStock) error) *PortfolioRepository_UpdatePortfolioStock_Call {
	_c.Call.Return(run)
	return _c
}

// NewPortfolioRepository creates a new instance of PortfolioRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioRepository {
	mock := &PortfolioRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
