// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kasaderos/camel/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

type TaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskRepository) EXPECT() *TaskRepository_Expecter {
	return &TaskRepository_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *TaskRepository) CreateTask(ctx context.Context, task model.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type TaskRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task model.Task
func (_e *TaskRepository_Expecter) CreateTask(ctx interface{}, task interface{}) *TaskRepository_CreateTask_Call {
	return &TaskRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *TaskRepository_CreateTask_Call) Run(run func(ctx context.Context, task model.Task)) *TaskRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Task))
	})
	return _c
}

func (_c *TaskRepository_CreateTask_Call) Return(_a0 error) *TaskRepository_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_CreateTask_Call) RunAndReturn(run func(context.Context, model.Task) error) *TaskRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// FetchTasks provides a mock function with given fields: ctx, portfolioID, statuses
func (_m *TaskRepository) FetchTasks(ctx context.Context, portfolioID string, statuses []model.TaskStatus) ([]model.Task, error) {
	ret := _m.Called(ctx, portfolioID, statuses)

	if len(ret) == 0 {
		panic("no return value specified for FetchTasks")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.TaskStatus) ([]model.Task, error)); ok {
		return rf(ctx, portfolioID, statuses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.TaskStatus) []model.Task); ok {
		r0 = rf(ctx, portfolioID, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []model.TaskStatus) error); ok {
		r1 = rf(ctx, portfolioID, statuses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_FetchTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTasks'
type TaskRepository_FetchTasks_Call struct {
	*mock.Call
}

// FetchTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - portfolioID string
//   - statuses []model.TaskStatus
func (_e *TaskRepository_Expecter) FetchTasks(ctx interface{}, portfolioID interface{}, statuses interface{}) *TaskRepository_FetchTasks_Call {
	return &TaskRepository_FetchTasks_Call{Call: _e.mock.On("FetchTasks", ctx, portfolioID, statuses)}
}

func (_c *TaskRepository_FetchTasks_Call) Run(run func(ctx context.Context, portfolioID string, statuses []model.TaskStatus)) *TaskRepository_FetchTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]model.TaskStatus))
	})
	return _c
}

func (_c *TaskRepository_FetchTasks_Call) Return(_a0 []model.Task, _a1 error) *TaskRepository_FetchTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_FetchTasks_Call) RunAndReturn(run func(context.Context, string, []model.TaskStatus) ([]model.Task, error)) *TaskRepository_FetchTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, task
func (_m *TaskRepository) UpdateTask(ctx context.Context, task model.UpdateTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UpdateTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type TaskRepository_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task model.UpdateTask
func (_e *TaskRepository_Expecter) UpdateTask(ctx interface{}, task interface{}) *TaskRepository_UpdateTask_Call {
	return &TaskRepository_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, task)}
}

func (_c *TaskRepository_UpdateTask_Call) Run(run func(ctx context.Context, task model.UpdateTask)) *TaskRepository_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UpdateTask))
	})
	return _c
}

func (_c *TaskRepository_UpdateTask_Call) Return(_a0 error) *TaskRepository_UpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_UpdateTask_Call) RunAndReturn(run func(context.Context, model.UpdateTask) error) *TaskRepository_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
