// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kasaderos/camel/internal/model"

	time "time"
)

// MarketProvider is an autogenerated mock type for the MarketProvider type
type MarketProvider struct {
	mock.Mock
}

type MarketProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketProvider) EXPECT() *MarketProvider_Expecter {
	return &MarketProvider_Expecter{mock: &_m.Mock}
}

// FetchBars provides a mock function with given fields: ctx, symbol, start, end
func (_m *MarketProvider) FetchBars(ctx context.Context, symbol string, start time.Time, end time.Time) ([]model.Bar, error) {
	ret := _m.Called(ctx, symbol, start, end)

	if len(ret) == 0 {
		panic("no return value specified for FetchBars")
	}

	var r0 []model.Bar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]model.Bar, error)); ok {
		return rf(ctx, symbol, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []model.Bar); ok {
		r0 = rf(ctx, symbol, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Bar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, symbol, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketProvider_FetchBars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBars'
type MarketProvider_FetchBars_Call struct {
	*mock.Call
}

// FetchBars is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - start time.Time
//   - end time.Time
func (_e *MarketProvider_Expecter) FetchBars(ctx interface{}, symbol interface{}, start interface{}, end interface{}) *MarketProvider_FetchBars_Call {
	return &MarketProvider_FetchBars_Call{Call: _e.mock.On("FetchBars", ctx, symbol, start, end)}
}

func (_c *MarketProvider_FetchBars_Call) Run(run func(ctx context.Context, symbol string, start time.Time, end time.Time)) *MarketProvider_FetchBars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MarketProvider_FetchBars_Call) Return(_a0 []model.Bar, _a1 error) *MarketProvider_FetchBars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketProvider_FetchBars_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]model.Bar, error)) *MarketProvider_FetchBars_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarketProvider creates a new instance of MarketProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketProvider {
	mock := &MarketProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
