// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kasaderos/camel/internal/model"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// FetchBars provides a mock function with given fields: ctx, assetID, start, end
func (_m *Repository) FetchBars(ctx context.Context, assetID string, start time.Time, end time.Time) ([]model.Bar, error) {
	ret := _m.Called(ctx, assetID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for FetchBars")
	}

	var r0 []model.Bar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]model.Bar, error)); ok {
		return rf(ctx, assetID, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []model.Bar); ok {
		r0 = rf(ctx, assetID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Bar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, assetID, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FetchBars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBars'
type Repository_FetchBars_Call struct {
	*mock.Call
}

// FetchBars is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - start time.Time
//   - end time.Time
func (_e *Repository_Expecter) FetchBars(ctx interface{}, assetID interface{}, start interface{}, end interface{}) *Repository_FetchBars_Call {
	return &Repository_FetchBars_Call{Call: _e.mock.On("FetchBars", ctx, assetID, start, end)}
}

func (_c *Repository_FetchBars_Call) Run(run func(ctx context.Context, assetID string, start time.Time, end time.Time)) *Repository_FetchBars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *Repository_FetchBars_Call) Return(_a0 []model.Bar, _a1 error) *Repository_FetchBars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FetchBars_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]model.Bar, error)) *Repository_FetchBars_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBars provides a mock function with given fields: ctx, assetID, bars
func (_m *Repository) SaveBars(ctx context.Context, assetID string, bars []model.Bar) error {
	ret := _m.Called(ctx, assetID, bars)

	if len(ret) == 0 {
		panic("no return value specified for SaveBars")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.Bar) error); ok {
		r0 = rf(ctx, assetID, bars)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SaveBars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBars'
type Repository_SaveBars_Call struct {
	*mock.Call
}

// SaveBars is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - bars []model.Bar
func (_e *Repository_Expecter) SaveBars(ctx interface{}, assetID interface{}, bars interface{}) *Repository_SaveBars_Call {
	return &Repository_SaveBars_Call{Call: _e.mock.On("SaveBars", ctx, assetID, bars)}
}

func (_c *Repository_SaveBars_Call) Run(run func(ctx context.Context, assetID string, bars []model.Bar)) *Repository_SaveBars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]model.Bar))
	})
	return _c
}

func (_c *Repository_SaveBars_Call) Return(_a0 error) *Repository_SaveBars_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SaveBars_Call) RunAndReturn(run func(context.Context, string, []model.Bar) error) *Repository_SaveBars_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
